### ISSUE TITLE
enhance xv so it can handle "webp" images.

### ISSUE THREAD

**Issue by not-a-sysadmin** [jasper-software/xv#7]
xv cannot handle "webp" images.  "webp" images do seem to be becoming more common.  So please enhance xv so it can correctly load webp images, and save images in the webp format.

**Comment by tanabi** [comment]
Hmm I'm looking into this a bit to see if its something I can reasonably add.  Never really looked at the code base before though it seems pretty well put together.

**Comment by not-a-sysadmin** [comment]
(replying to "tanabi")
Thank-you!

(replying to "mdadams")
I did know that John Bradley engineered xv.  I get the impression that he abandoned it sometime during or after 2007?  2009?  I've been using it on a Fedora workstation since 2013.  I've noticed fixes and improvements all during those 10 years.  So apparently someone has been maintaining/enhancing it.  The version that I have is labelled "3.10a.jumbopatch.20070520", release "42.fc37".

**Comment by tanabi** [comment]
@not-a-sysadmin I've used it since I went to college ... cerca 1996-ish +/- a few years.  I even registered a copy when I graduated (all you got was instructions on what lines to change in the code to make it not say UNREGISTERED anymore :D).  There's still not another program that has the same set of features ... there's a lot I can do with xv that would take 2 separate softwares (one of them being GIMP which is a freaking 10 ton gorilla) so I still use it.

I'd debate the still being maintained thing -- I don't think anyone's really messed with the code since 2008 (I have a 2008 version from the last .deb release of it).  I'd love to see it back on the package managers and installed by yum/apt/etc. but I don't know how that works or have the time to figure it out.

That said, I've been looking at webp libraries and I am planning on taking a stab at the support this weekend.

**Comment by mdadams** [comment]
To the best of my understanding, John Bradley no longer does any development work on xv and it has been this way for a long time (probably since 2007, like you said).  Due to the popularity of this software, however, this software is packaged by many projects including numerous Linux and BSD distributions.  There are many patches and bug fixes that have been made to the xv software over the years.  Many of them have been collected together and applied to the code base in this Git repository, including the jumbo patchset that you mention.  I believe that the maintainer of xv for Fedora uses this Git repository to generate the xv package for Fedora.  I am not sure if any other Linux or BSD distributions are currently using this repository.

**Comment by tanabi** [comment]
Loading webp images turned out to be nearly trivial.  I need to sort out writing webp images which is going to be somewhat more fiddly, but at the very least I now have a functioning loader.

**Comment by tanabi** [comment]
@not-a-sysadmin I was able to add in the support.  See my release notes here https://github.com/jasper-software/xv/pull/8 for full details.  You can either grab the code from my repo now or hopefully it passes muster for @mdadams to merge it here :)

**Comment by not-a-sysadmin** [comment]
Thank-you, @tanabi ,  for your time and effort.  I don't know the process, and I don't know if there's something I have to do, for the upgrades to reach the appropriate Fedora repository (rpmfusion-nonfree, I think).  Then Fedora's "dnf" command should handle everything, including dependencies such as libwebp-dev, assuming the rpm is set up correctly.

As my "handle" says, I'm not a system administrator.  So I'll have to wait for the enhancements to reach the Fedora repository for me to try out your enhancements.

Curious:
The Fedora "dnf" command seems to say that xv is in two Fedora repositories:
-----
bash.6[.orig_pics]: dnf provides xv
Last metadata expiration check: 2:06:07 ago on Sun 30 Apr 2023 01:47:52 PM MDT.
xv-3.10a.jumbopatch.20070520-42.fc37.x86_64 : Interactive image display program
                                            : for X
Repo        : @System
Matched from:
Provide    : xv = 3.10a.jumbopatch.20070520-42.fc37

xv-3.10a.jumbopatch.20070520-42.fc37.x86_64 : Interactive image display program
                                            : for X
Repo        : rpmfusion-nonfree
Matched from:
Provide    : xv = 3.10a.jumbopatch.20070520-42.fc37

bash.7[.orig_pics]:
-----

@mdadams and @tanabi: Is there something I should do to get these enhancements into the appropriate Fedora repository?

**Comment by tanabi** [comment]
@not-a-sysadmin I don't really know how that process works at all :)  However, downloading, building, and installing a local copy is very very easy and covered in the INSTALL.txt file.  You will need to install the compiling tools on your machine.  I'm a ubuntu guy so I can't really help you too much with Fedora stuff, but you'll need:

* cmake
* a c compiler (probably already installed, might come for the ride with cmake)
* libjpeg-devel (it's -dev on ubuntu, but I think Fedora uses -devel)
* libtiff-devel
* libwebp-devel
* libxt-devel

If you search like "libjpeg development package for fedora" or the like you'll get the package names, that's how I usually figure them out for ubuntu if I can't guess at them.

**Comment by mdadams** [comment]
@tanabi  and @not-a-sysadmin: Typically, each package in a Linux distribution has a maintainer that looks after the packaging of that package.  It is my understanding that  [Paul Howarth](https://github.com/pghmcfc) is the xv packager for Fedora.  I asked Paul to review the PR to see if he is okay with it.  I am not a package maintainer myself.  A far as I am aware, Fedora builds its xv package from the code in this repository.  I don't know if any other Linux distributions use it, however.

**Comment by pghmcfc** [comment]
Hi guys, I am one of the packagers for RPM Fusion, which is where the "Fedora" xv package lives. Up until now the RPM Fusion package has been built from the original xv-3.10a sources plus lots of patches, some of which came from this very repository on GitHub. However, with the addition of webp support and hence the new library to link against, I've finally bitten the bullet and switched over to the 4.1.1 release and built it using cmake. It's just been built in RPM Fusion for Fedora 37, 38 and Rawhide, and should be in the "testing" repositories in a day or two. I think it lives there for a week or two before it's pushed to the main release repository.

**Comment by not-a-sysadmin** [comment]
This new release was installed on my Fedora-37 workstation today.  I gave it a good test drive.  It works great for "webp" images.  Thank-you, tanabi,  Michael, and Paul.

**Comment by tanabi** [comment]
@not-a-sysadmin You're welcome!
